#!/bin/bash
chmod --reference-
[master 7d73b81] Switch current user to betty
 10 files changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 0x01-shell_permissions/Create
 delete mode 100644 0x01-shell_permissions/a
 delete mode 100644 0x01-shell_permissions/betty.
 delete mode 100644 0x01-shell_permissions/current
 delete mode 100644 0x01-shell_permissions/script
 delete mode 100644 0x01-shell_permissions/switches
 delete mode 100644 0x01-shell_permissions/that
 delete mode 100644 0x01-shell_permissions/the
 delete mode 100644 0x01-shell_permissions/to
 delete mode 100644 0x01-shell_permissions/user
